version: '3.9'
services:
  proxy:
    image: nginx:1.21.0
    container_name: nginx-sample_proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/html:/etc/nginx/html
    ports:
      - '80:80'
    depends_on:
      - api
      - web

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nginx-sample_api
    command: yarn dev
    volumes:
      - ./api:/app
    tty: true

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: nginx-sample_web
    command: yarn dev
    volumes:
      - ./web:/app
    tty: true
    environment:
      PORT: 3000
      HOST: 0.0.0.0
